spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://optiyadb:3306/optiya_eventlog?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
        username: root
        password: Optiya5576
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL57Dialect
        hibernate:
               ddl-auto: update
               
        properties:
              javax:
                 persistence:
                      sharedCache: 
                           mode: ENABLE_SELECTIVE
              
              hibernate:
                    generate_statistics: false
                    cache:
                      use_second_level_cache: true
                      use_query_cache: true 
                      region:
                           factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory 
    mail:
        host: smtp.gmail.com
        port: 587
        username: usmanmuradjamali@gmail.com
        password: vxhhscqdadhegzma
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true            
      
server:
    port: 9099
    
optiya:
    imageServer: https://dev.optiya.com:3030
    imageDirectoryLocation: /opt/optiya/images
    kafka:
        messageServer: dev.optiya.com:9092
        messageSchemaServer: http://dev.optiya.com:8081
    event:
        topic: EVENT-LOG-SERVICE
    dbsync:
        topic: DATABASE-SYNC-SERVICE
    anpr:
        request:
            topic: ANPR-REQUEST-SERVICE
        response:
            topic: ANPR-RESPONSE-LANE-0
        engine: ULTIMATEALPR
        timeout: 3000
        
management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
    secret: Jahan
   
            
openapi:
    title: Optiya
    version: 1.0
    description: Optiya Event Log Api Documentation
    
springdoc:
    swagger-ui:
        enabled: false
    api-docs:
        path: /api
            
logging:
  level:
    org:
      hibernate:
        type: trace
