server:
    port: 9999
    
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: get
        uri: http://httpbin.org:80
        predicates:
        - Path=/get
      - id: pet
        uri: lb://SSO-SERVICE/users/find/1
        predicates:
        - Path=/pet
      
eureka:
    instance:
        hostname: localhost
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2

    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: ${EUREKA_URL:http://localhost:9761/eureka/}
