server:
    port: 9090
    
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: sso-service
          uri: lb://SSO-SERVICE
          predicates:
            - Path=/sso/**
          filters:
            - StripPrefix=1
        - id: tenant-service
          uri: lb://TENANT-SERVICE
          predicates:
            - Path=/tenant/**
          filters:
            - StripPrefix=1
        - id: docs-service
          uri: lb://DOCS-SERVICE
          predicates:
            - Path=/docs/**
          filters:
            - StripPrefix=1
        
management:
  endpoints:
    web:
      exposure:
        include: "*"

   

