server:
    port: 9090
    
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: get
        uri: http://httpbin.org:80
        predicates:
        - Path=/get
      - id: pet
        uri: http://localhost:9091/actuator/health
        predicates:
        - Path=/pet
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
      
eureka:
    instance:
        hostname: localhost
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2

    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: ${EUREKA_URL:http://localhost:9761/eureka/}
