server:
    port: 9090
    
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: sso-service
          uri: lb://SSO-SERVICE
          predicates:
            - Path=/sso/**
          filters:
            - StripPrefix=1
        
management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
    secret: Jahan
    jwtExpirationInSec: 10000
    
eureka:
    instance:
        hostname: localhost
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2

    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: ${EUREKA_URL:http://localhost:9761/eureka/}
