spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/optiya_sso
        username: optiya
        password: optiya
    jpa:
        show-sql: true
        properties:
              javax:
                 persistence:
                      sharedCache: 
                           mode: ENABLE_SELECTIVE
              
              hibernate:
                   ddl-auto: update
                   generate_statistics: true
                   cache:
                      use_second_level_cache: true
                      use_query_cache: true 
                      region:
                           factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory 
server:
    port: 9091
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
    secret: Jahan
    jwtExpirationInSec: 10000
    
eureka:
    instance:
        hostname: localhost
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2

    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: ${EUREKA_URL:http://localhost:9761/eureka/}
            
logging:
  level:
    org:
      hibernate:
        type: trace
